[tool.black]
line-length = 120

[tool.pytest.ini_options]
env = [
  "OPENAPI_KEY=OPENAPI_KEY",
  "DB_FILE=./tests/history.sqlite3",
  "LIMIT_FILE_SIZE=5"
]

[tool.mypy]
ignore_missing_imports = true
exclude = ["venv/"]
strict = true
